### ISSUE TITLE
Where is the this plugin's change log?

### ISSUE THREAD

**Issue by nsdnsg** [euOnmyoji/NewHonor-plugin-for-sponge#11]
This plugin  is very gwood!But where is the this plugin's change log?

**Comment by KunoSayo** [comment]
I was too lazy to write full change log.
You may found small change log in the tags.
[https://github.com/EpicBanItemTeam/NewHonor/tags](https://github.com/EpicBanItemTeam/NewHonor/tags)

Or follow the commit log.

**Comment by nsdnsg** [comment]
Who are you？

在 2020-08-28 08:42:52，yinyangshi <notifications@github.com> 写道：


I was too lazy to write full change log.
You may found small change log in the tags.
https://github.com/EpicBanItemTeam/NewHonor/tags

Or follow the commit log.
