### ISSUE TITLE
Permission manage

### ISSUE THREAD

**Issue by galoti** [euOnmyoji/NewHonor-plugin-for-sponge#5]
Tested versions: NewHonor-2.4.0-b321-SpongeAPI7.1.0 and NewHonor-2.3.0-b300

   Hello!!! I'm using the "permission-manage" option, and the player doesn't lose the Honor when I remove the permission.

**Comment by KunoSayo** [comment]
Sorry!\
v2.4.2 fixed.\
Thanks for telling!
